create database opt_db;

DROP TABLE IF EXISTS opt_orders;
DROP TABLE IF EXISTS opt_products;
DROP TABLE IF EXISTS opt_clients;

CREATE TABLE IF NOT EXISTS opt_clients (
    id UUID PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    surname VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    phone VARCHAR(50) NOT NULL,
    address TEXT NOT NULL,
    status VARCHAR(20) NOT NULL CHECK (status IN ('active', 'inactive'))
);

CREATE TABLE IF NOT EXISTS opt_products (
    product_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_name VARCHAR(255) NOT NULL,
    product_category VARCHAR(50) NOT NULL CHECK (
        product_category IN ('Category1', 'Category2', 'Category3', 'Category4', 'Category5')
    ),
    description TEXT
);

CREATE TABLE IF NOT EXISTS opt_orders (
    order_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_date DATE NOT NULL,
    client_id UUID,
    product_id INTEGER,
    CONSTRAINT fk_opt_orders_client
        FOREIGN KEY (client_id) REFERENCES opt_clients(id),
    CONSTRAINT fk_opt_orders_product
        FOREIGN KEY (product_id) REFERENCES opt_products(product_id)
);

--запит повертає кількість замовлень старих та нових клієнтів

--нeоптимізований запит

explain analyze
select 
	(--сума замовлень
	select sum(orders_count) as new_clients_orders_count
	from 
		--активні клієнти
		(select * 
		from 
			(select  
				c.id, 
				c.name, 
				c.surname, 
				count(o.order_id) as orders_count, 
				min(o.order_date) as first_order_date
			from opt_clients as c 
			join opt_orders as o
			on c.id = o.client_id
			where c.status = 'active'
			group by c.id, c.name, c.surname)
		--нові клієнти
		where first_order_date >= '2025-01-01')),
	(
	--сума замовлень
	select sum(orders_count) as old_clients_orders_count
	from 
		--активні клієнти
		(select * 
		from 
			(select  
				c.id, 
				c.name, 
				c.surname, 
				count(o.order_id) as orders_count, 
				min(o.order_date) as first_order_date
			from opt_clients as c 
			join opt_orders as o
			on c.id = o.client_id
			where c.status = 'active'
			group by c.id, c.name, c.surname)
	--старі клієнти
	where first_order_date <= '2022-01-01')
	)

--створбємо індекси для opt_orders(client_id), opt_clients(status), opt_orders(order_date)
--тому, що потім фільтрація відбувається саме по цих значеннях

create index if not exists inx_opt_orders_clients_id 
	on opt_orders(client_id);
create index if not exists inx_opt_clients_status 
	on opt_clients(status);
create index if not exists inx_opt_orders_order_date
	on opt_orders(order_date);

--виконувала запит з цією командою і без неї - детальніше в файлі зі звітом про оптимізацію
set enable_seqscan = off;
explain analyze
--cte, що повертає активних клієнтів
with active_clients as(
	select  
		c.id, 
		c.name, 
		c.surname, 
		--кількість замовлень одного клієнта
		count(o.order_id) as orders_count,
		--дата, коли було зроблено перше замовлення
		min(o.order_date) as first_order_date
	from opt_clients as c 
	join opt_orders as o
	on c.id = o.client_id
	where c.status = 'active'
	group by c.id, c.name, c.surname),
--старі клієнти - в яких перше замовлення було зроблено раніше за 2022-01-01
old_active_clients as( 
	select * 
	from active_clients
	where first_order_date <= '2022-01-01'),
-- нові - пізніше за 2025-01-01
new_active_clients as(
	select * 
	from active_clients
	where first_order_date >= '2025-01-01')
--фінальний запит рахує суму всіх замовлень нових клієнтів і старих, виводить дві колонки і один рядок
select 
(select sum(orders_count) as new_clients_orders_count
from new_active_clients),
(select sum(orders_count) as old_clients_orders_count
from old_active_clients)
